"""Test configuration and sample data constants."""

# Test data prefixes (helps identify test data for cleanup)
TEST_PREFIX = "test_"

# --- Test Roles ---
# We no longer need a test role ID, as we will fetch the real one.

# --- Sample User IDs (matching Firebase Auth UIDs) ---
TEST_PASS_STUDENT_ID = f"{TEST_PREFIX}user_pass_original"
TEST_FAIL_STUDENT_ID = f"{TEST_PREFIX}user_fail_original"
TEST_FACULTY_ID = f"{TEST_PREFIX}user_faculty_001"
TEST_ADMIN_ID = f"{TEST_PREFIX}user_admin_001"

# --- Sample Document IDs ---
TEST_SUBJECT_ID = f"{TEST_PREFIX}subj_personality"
TEST_TOS_ID = f"{TEST_PREFIX}tos_personality_v1"

# --- NEW: Expanded Content Library ---
# We define all content here so the populate script can create it
# and then generate student activities based on it.

TEST_MODULES_DATA = [
    {"id": f"{TEST_PREFIX}mod_rem_01", "title": "Introduction to Personality", "bloom_level": "remembering"},
    {"id": f"{TEST_PREFIX}mod_rem_02", "title": "Key Terms and Definitions", "bloom_level": "remembering"},
    {"id": f"{TEST_PREFIX}mod_und_01", "title": "Explaining Psychoanalytic Theory", "bloom_level": "understanding"},
    {"id": f"{TEST_PREFIX}mod_und_02", "title": "Summarizing Humanistic Approaches", "bloom_level": "understanding"},
    {"id": f"{TEST_PREFIX}mod_app_01", "title": "Applying Trait Theory", "bloom_level": "applying"},
    {"id": f"{TEST_PREFIX}mod_app_02", "title": "Behavioral Theory in Practice", "bloom_level": "applying"},
    {"id": f"{TEST_PREFIX}mod_ana_01", "title": "Analyzing Case Studies (Cognitive)", "bloom_level": "analyzing"},
    {"id": f"{TEST_PREFIX}mod_ana_02", "title": "Contrasting Theories", "bloom_level": "analyzing"},
]

TEST_QUIZZES_DATA = [
    {"id": f"{TEST_PREFIX}quiz_rem_01", "title": "Definitions Quiz", "bloom_level": "remembering"},
    {"id": f"{TEST_PREFIX}quiz_und_01", "title": "Theory Summary Quiz", "bloom_level": "understanding"},
    {"id": f"{TEST_PREFIX}quiz_app_01", "title": "Case Study Application 1", "bloom_level": "applying"},
    {"id": f"{TEST_PREFIX}quiz_ana_01", "title": "Analysis Quiz", "bloom_level": "analyzing"},
]

# All test activities are generated by the script now.
# All test assessments are generated by the script now.
TEST_RECOMMENDATION_IDS = [
    f"{TEST_PREFIX}rec_001",
    f"{TEST_PREFIX}rec_002"
]

# --- Base Student Data (Original 2) ---

SAMPLE_PASS_STUDENT_DATA = {
    "email": "test.pass.original@example.com",
    "first_name": "OriginalPass",
    "last_name": "Student",
    "pre_assessment_score": 85.0
}

SAMPLE_FAIL_STUDENT_DATA = {
    "email": "test.fail.original@example.com",
    "first_name": "OriginalFail",
    "last_name": "Student",
    "pre_assessment_score": 42.0
}

# --- NEW: 10 Additional Students for Reliability Testing ---
# Personas:
# - high_achiever (Pass): Scores 85-100
# - struggler (Fail): Scores 40-65
# - poor_application (Fail): Scores 90-100 on remembering/understanding, but 40-60 on applying/analyzing
# - good_crammer (Pass): Scores 50-70 on remembering/understanding, but 85-100 on applying/analyzing

ADDITIONAL_STUDENT_DATA = [
    # 1. (Pass) High performer
    {
        "id": f"{TEST_PREFIX}user_student_01",
        "data": {"email": "student01@example.com", "first_name": "Alice", "last_name": "Adams", "pre_assessment_score": 90.0},
        "persona": "high_achiever"
    },
    # 2. (Fail) Low performer
    {
        "id": f"{TEST_PREFIX}user_student_02",
        "data": {"email": "student02@example.com", "first_name": "Bob", "last_name": "Brown", "pre_assessment_score": 40.0},
        "persona": "struggler"
    },
    # 3. (Fail) Poor Application
    {
        "id": f"{TEST_PREFIX}user_student_03",
        "data": {"email": "student03@example.com", "first_name": "Carol", "last_name": "Clark", "pre_assessment_score": 70.0},
        "persona": "poor_application"
    },
    # 4. (Fail) Poor Application
    {
        "id": f"{TEST_PREFIX}user_student_04",
        "data": {"email": "student04@example.com", "first_name": "David", "last_name": "Davis", "pre_assessment_score": 68.0},
        "persona": "poor_application"
    },
    # 5. (Pass) Good Crammer
    {
        "id": f"{TEST_PREFIX}user_student_05",
        "data": {"email": "student05@example.com", "first_name": "Eve", "last_name": "Evans", "pre_assessment_score": 65.0},
        "persona": "good_crammer"
    },
    # 6. (Pass) Good Crammer
    {
        "id": f"{TEST_PREFIX}user_student_06",
        "data": {"email": "student06@example.com", "first_name": "Frank", "last_name": "Finn", "pre_assessment_score": 50.0},
        "persona": "good_crammer"
    },
    # 7. (Pass) High performer
    {
        "id": f"{TEST_PREFIX}user_student_07",
        "data": {"email": "student07@example.com", "first_name": "Grace", "last_name": "Green", "pre_assessment_score": 82.0},
        "persona": "high_achiever"
    },
    # 8. (Fail) Low performer
    {
        "id": f"{TEST_PREFIX}user_student_08",
        "data": {"email": "student08@example.com", "first_name": "Heidi", "last_name": "Hall", "pre_assessment_score": 72.0},
        "persona": "struggler"
    },
    # 9. (Fail) Low performer
    {
        "id": f"{TEST_PREFIX}user_student_09",
        "data": {"email": "student09@example.com", "first_name": "Ivan", "last_name": "Ingram", "pre_assessment_score": 60.0},
        "persona": "struggler"
    },
    # 10. (Pass) High performer
    {
        "id": f"{TEST_PREFIX}user_student_10",
        "data": {"email": "student10@example.com", "first_name": "Judy", "last_name": "Jones", "pre_assessment_score": 80.0},
        "persona": "high_achiever"
    }
]


# --- Other Sample Data (Unchanged) ---

SAMPLE_SUBJECT_DATA = {
    "subject_name": "Advanced Theories of Personality (Test)",
    "pqf_level": 7,
    "active_tos_id": TEST_TOS_ID
}

SAMPLE_TOS_DATA = {
    "subject_name": "Advanced Theories of Personality (Test)",
    "pqf_level": 7,
    "difficulty_distribution": {"easy": 0.30, "moderate": 0.40, "difficult": 0.30},
    "content": [
        {
            "title": "Theories",
            "sub_content": [
                {
                    "purpose": "Cite major tenets of personality theories",
                    "blooms_taxonomy": [{"remembering": 8}]
                }
            ],
            "no_items": 40,
            "weight_total": 0.40
        }
    ],
    "total_items": 100
}

