name: Run Daily AI Predictions

on:
  schedule:
    # Runs at 3:00 AM UTC every day (you can change '3' to any hour)
    - cron: '0 3 * * *'
  # This line also lets you run it manually from the GitHub "Actions" tab
  workflow_dispatch:

jobs:
  build-and-predict:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install "heavy" dependencies
        run: |
          pip install -r requirements-ml.txt

      - name: Run the prediction script
        env:
          # This is where the magic happens.
          # It reads the secret you will add to GitHub.
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          python ./ml/run_batch_predictions.py